name = "gokz-overlay"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[durable_objects]
bindings = [
  { name = "WEBSOCKET_MANAGER", class_name = "WebSocketManager" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebSocketManager"]

